baseurl = "https://pcsentral.netlify.app"
languageCode = "id-ID"
title = "PCsentral"

defaultContentLanguage = "id"

hasCJKLanguage = false

disqusShortname = ""

[pagination]
pagerSize = 5

theme = "github.com/CaiJimmy/hugo-theme-stack/v3.30.0"

[module]
  [[module.imports]]
    path = "github.com/CaiJimmy/hugo-theme-stack/v3.30.0"

  [module.hugoVersion]
    min = "0.147.8"
    extended = true
