[build]
  command = "hugo --gc --minify"
  publish = "public"

# Global default environment
[context.production]
  command = "hugo --gc --minify --enableGitInfo"

[context.production.environment]
  HUGO_VERSION = "0.147.8"
  HUGO_ENABLEGITINFO = "true"
  HUGO_ENV = "production"
  HUGO_BASEURL = "https://pcsentral.netlify.app"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.develop.environment]
  HUGO_BASEURL = "http://localhost:1313"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
